name: share_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  card_swiper: ^2.0.4
  shared_preferences: ^2.0.15
  vector_math: ^2.1.2
  url_launcher: ^6.1.6
  pull_to_refresh: ^2.0.0
  crypto: ^3.0.2
  path: ^1.8.2
  image_picker: ^0.8.5+3
  flutter_screenutil: ^5.5.4
  flutter_native_splash: ^2.2.10
  get: 4.6.5
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/images/
  fonts: 
    - family: iconfont
      fonts: 
        - asset: assets/fonts/iconfont.ttf
  uses-material-design: true

flutter_native_splash: 
  color: '#f9f4dc'
  color_dark: '#660000'
  image: assets/images/logo.png

